// @flow
export type Listing = {
    id: number,
    item_name: string,
    has_variations: string,
    is_variant: string,
    parent_listing_id: ?string,
    store_id: string,
    supplier_url: ?string,
    supplier: ?string,
    supplier_id: ?string,
    store_url: string,
    store: string,
    store_id: string,
    product_availability: ?string | ?number,
    new_price: ?string,
    refactored_price: ?string,
    price: ?string,
    last_repriced: string,
    created_at: string,
    image: ?string,
    refactored_percentage: ?string,
    local_refactor_percentage: ?string,
    gross_profit: ?string,
    global_refactor_settings: string,
    local_refactor_settings: ?{
        add_amazon_fee: string,
        add_ebay_fee: string,
        add_paypal_fee: string,
        add_state_tax: string,
        add_vat: string,
        vat_percentage: string,
        amazon_fee_percentage: string,
        ebay_fee: string,
        minimum_price: string,
        maximum_price: string,
        paypal_fee_percentage: string,
        paypal_fixed_fee: string,
        refactor_fixed_sum: string,
        refactor_percentage: string,
        use_refactor_percentage: string,
        state_tax_percentage: string
    },
    use_maximum_price: string
 };